development:
  host: localhost
  database: notification_development

test:
  host: localhost
  database: notification_test

# set these environment variables on your prod server
production:
  host: localhost
  database: notification_pro
  uri: <%= ENV['MONGOHQ_URL'] %>
