development:
  host: localhost
  database: notification_development

test:
  host: localhost
  database: notification_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
